import {
  EllipseGraphics,
  EllipsoidGraphics,
  PolygonGraphics,
  PolylineGraphics,
  PolylineVolumeGraphics,
  BoxGraphics,
  CorridorGraphics,
  CylinderGraphics,
  LabelGraphics,
  BillboardGraphics,
  ModelGraphics,
  PathGraphics,
  PointGraphics,
  RectangleGraphics,
  WallGraphics,
} from 'cesium';

export enum GraphicsType {
  ellipse = EllipseGraphics,
  ellipsoid = EllipsoidGraphics,
  polygon = PolygonGraphics,
  polyline = PolylineGraphics,
  polylineVolume = PolylineVolumeGraphics,
  box = BoxGraphics,
  corridor = CorridorGraphics,
  cylinder = CylinderGraphics,
  label = LabelGraphics,
  billboard = BillboardGraphics,
  model = ModelGraphics,
  path = PathGraphics,
  point = PointGraphics,
  rectangle = RectangleGraphics,
  wall = WallGraphics,
}
